actualbudget/actual-server

- Dockerfile
The Node slim image did not contain all needed packages to successfully build Actual. Changing to the standard image fixed the build process.
For reference, this is the error that popped up with the slim image:
```
=> ERROR [6/8] RUN yarn install --production                                                                                                                                                                            7.2s
------
> [6/8] RUN yarn install --production:
#0 0.131 yarn install v1.22.18
#0 0.170 [1/4] Resolving packages...
#0 0.243 [2/4] Fetching packages...
#0 6.143 [3/4] Linking dependencies...
#0 6.144 warning " > eslint-config-react-app@3.0.6" has incorrect peer dependency "babel-eslint@9.x".
#0 6.144 warning " > eslint-config-react-app@3.0.6" has incorrect peer …
```
> Adjust Dockerfile to build successfully

- app.js
- load-config.js
Added an option in the config file to bind to a given hostname (e.g. `localhost`). I intend to run the server behind a reverse proxy and I want to bind it localhost, so I thought others may also use this option :)
I've left the default to `0.0.0.0` in order to not break the current behavior.
> Add hostname binding

- tsconfig.json
This configures TypeScript and tells it to look at JS files as well, so that IDEs like VSCode can provide better edit-time checks.
This works especially well in VSCode with the ErrorLens extension which shows problems inline.
Problems with typings can be resolved by adding JSDoc comments (for which homer0 has an excellent Prettier plugin) or straight-up `*.d.ts` files, which will be used by the editor but otherwise don't impact the build at all.
This is a stepping stone towards TypeScript support, allowing a gradual conversion. Personally I use TS very sparingly, rely extensively on JSDoc and have great expectations for the [types proposal](https://github.com/sirisian/ecmascript-types).
> add: tsconfig.json

- Dockerfile
As described by [brtwrst](https://github.com/brtwrst) in my last pull request #1 , a multi-stage build reduces the final image size to the minimum.
I have not made changes to the first ADD command as I have no idea which files definitely need to be in the final image.
> Adjust Dockerfile to use multi-stage builds

- README.md
I thought i'd add some instructions for getting up and running with the `Dockerfile` that's in the repo
> Instructions for running via Docker

- Dockerfile
This change reduces image size by 80% 
```
actual-alpine   latest            61b69b88643e   12 minutes ago   192MB
actual-debian   latest            43fa732027dc   17 minutes ago   1.09GB
```
Also use [tini](https://github.com/krallin/tini) as "container init" allowing a gracefully shutdown of container
> Use Alpine Linux as base image for docker container

- app.js
- package.json
- yarn.lock
I run everything on my K8s cluster, so a health check endpoint would be optimal. The container could make use of this health check too.
This pr adds the simple express-actuator middleware, which provides:
```
/health
{
"status": "UP"
}
```
```
/info
{
"build": {
"name": "actual-sync",
"description": "actual syncing server",
"version": "1.0.0"
}
}
```
```
/metrics
{
"mem": {
"rss": 45621248,
"heapTotal": 22167552,
"heapUsed": 20089648,
"external": 949596,
"arrayBuffers": 45238
},
"uptime": 349.9881051
}
```
> Health Check Endpoint

- Dockerfile
- Dockerfile.alpine
This PR adds a separate `Dockerfile.alpine` to build an image based on Alpine Linux.
The resulting image will be just over 100M in size. 
The build and resulting image works on AMD64 (Tested on Ubuntu 20.04) and ARM64 (Tested on a RPI3 with Ubuntu 22.04)
During testing i switched between the `yarn start` and `node app.js` start commands and when using the latter, the container will exit with code 143 (which i think is the correct code) as opposed to exit code 1 when using `yarn start`. 
So i included the `node app.js` command for now.
> Add Dockerfile.alpine for alpine buil; add tini to debian image

- fly.template.toml
Deployments to fly.io were failing with error:
> Failed due to unhealthy allocations
Fixes #16
> Correct fly template port

- .github/workflows/build.yml
- README.md
Add Github Actions workflow to automatically build a Docker image on the creation of tags to version the changes of the Actual server. The Docker image is pushed to both the Docker Hub and the Github Container Registry.
Caution: the following variables/secrets must be configured by the maintainer in the project settings:
- `DOCKERHUB_USERNAME` - User name on the Docker Hub
- `DOCKERHUB_TOKEN` - Token instead of a password, can be created in the Docker Hub [account settings](https://hub.docker.com/settings/security)
> Add Github Actions workflow to automatically build a Docker image

- .eslintignore
- .eslintrc.js
- .prettierrc.json
- app-account.js
- app-sync.js
- migrations/1632571489012_remove_cache.js
- package.json
- util/error-middleware.js
- util/handle-error.js
- yarn.lock
Currently the linting setup is designed around a creating a React app and so isn't particularly useful for us. I've switched us over to use a Typescript compatible linting setup.
This does require a Typescript install however I'm expecting that we're going to have this anyway from #28 so it's not extra overhead.
> Add more appropriate linting setup

- app.js
This is the fix which enables an entirely different storage layer for Actual, and fixes all syncing/file issues with it. 
This took a while because I needed to get https://github.com/actualbudget/actual/pull/71 in first. I haven't released that change yet, but will do that this weekend. Once it's merged, I'll merge this PR.
You should export your data first before updating to this PR. The new storage layer will likely not be able to read your old data so it's really import that you'll be able to import your old data.
> Fix Cross-Origin issues to enable `SharedArrayBuffer`

- util/error-middleware.js
Error handling middleware functions must have four arguments to
identify it as such.
Fixes #40
See https://expressjs.com/en/api.html
>Error-handling middleware always takes four arguments. You must provide four arguments to identify it as an error-handling middleware function. Even if you don’t need to use the next object, you must specify it to maintain the signature. Otherwise, the next object will be interpreted as regular middleware and will fail to handle errors.
> fix: error handling middleware signature

- fly.template.toml
Fly deployments with the previous template setting are running without tini's subreaper capabilities (see logs in #54). 
This change enables tini as a subreaper in that environment.
> build: add tini subreaper arg to fly template

- fly.template.toml
Fly deployments on the free tier have ~256mb of memory available. Users with large transaction histories were encountering out of memory errors when attempting to export their data (#54).
This commit adds a node argument to (more or less) run the garbage collector at a smaller memory usage, helping keep users on flyio within their available limit. I think there are additional improvements to be made with the download process, but this config change is also useful.
> build: add node GC argument to fly template

- app-sync.js
- sql/messages.sql
- sync-simple.js
**This is a breaking change.** Ideally, users could simply do a "sync reset" and it would just work though.
This PR completely changes how sync data is stored on the server. Previously, I attempted to run a headless version of the entire Actual app. It loads in the full backend of Actual from npm and runs it. The theory was that the app syncing was very stable, given all the stable usage in the closed source version. The server would be just another normal client.
However, the Actual backend hadn't been run on the server like that before, and it wasn't stable. Things like posting schedules is weird to run on the server (and probably shouldn't be). Syncing also hadn't been run as a fully decentralized system. While the algorithm itself totally works like that, there's all kinds of little …
> Switch syncing to simple sync method

- app-sync.js
- load-config.js
- sync-simple.js
The new sync method merged in https://github.com/actualbudget/actual-server/pull/75 doesn't respect the `user-files` configuration. I also realized we were still initializing the full Actual app.
> Respect configuration for user-files and don't init the app

- app-sync.js
- package.json
- sync-simple.js
- util/paths.js
- yarn.lock
This is the last piece needed before releasing the new sync strategy. We should just write down the zip blobs directly instead of unzipping them; this also means we can turn back on e2e encryption if we want.
> Store user files as blobs instead of unzipping them

- .github/workflows/docker.yml
~~Facilitates folks trying out any new merged changes, not just ones the project considers "ready for release."
Didn't include here, but we might also consider building on every git tag, since those are rare.~~
PR has changed a lot based on feedback. 
[See below for details](https://github.com/actualbudget/actual-server/pull/82#issuecomment-1276136334).
Merging this change will result in Docker images with the following tags being built on every push to `master`:
`edge`
`sha-<commit_sha>`
(as well as the same tags suffixed with `-alpine`)
When a git tag containing `v*.*.*` is pushed to the repo, e.g. `v3.1.4` (or even `v1.2.3-long-description`, see Usage below), the following tagged Docker images will be built:
`latest`
`3.1`
`3.1.4`
`sha-<commit_sha>`
(as well as the same tags suffixed …
> Build docker image on push to master or tag

- load-config.js
Fixes #108 
Listening on '::' will make node listen on IPv4 as well as IPv6 addresses.
> fix: listen also listen on ipv6 addresses

- .editorconfig
- package.json
- yarn.lock
Upgrading `@actual-app/api` to 4.1.6: this will also upgrade node-fetch to v2 and thus fix security problems we have here.
Upgrade PR in api: https://github.com/actualbudget/actual/pull/609
> :arrow_up:  upgrade @actual-app/api to 4.1.6: node-fetch v2 support

- package.json
- yarn.lock
Upgrading dependencies.
- bcrypt from 5.0.1 to 5.1.0 - [changelog](https://github.com/kelektiv/node.bcrypt.js/blob/master/CHANGELOG.md)
- body-parser from 1.19.2 to 1.20.1 - [changelog](https://github.com/expressjs/body-parser/releases)
- express from 4.17.3 to 4.18.2 - [changelog](https://expressjs.com/en/changelog/4x.html)
- express-actuator from 1.8.1 to 1.8.4 - [changelog](https://github.com/rcruzper/express-actuator/releases)
> :arrow_up:  upgrade express*, bcrypt and body-parser

- app.js
- config-types.ts
- load-config.js
- Now all config properties can be set via environment variables (will PR the docs to add them there too!)
- a new `webRoot` config property allows you to skip using the web UI installed from npm and instead use a different version. The only requirement is that it has an `index.html`.
> Improve the server config

- app.js
\*shakes fist at CodeQL for suggesting changing this code\*
I didn’t test the change in 58d13003d32ca25d333d67a30b7e96bd2c367e40 thoroughly enough, sorry!
Fixes #126
> Fix / route returning the wrong MIME type

- README.md
- app.js
- load-config.js
This makes it easier to specify them as an environment variable (where you might not be able to enter a multiline string). It does not apply to the contents of a file pointed to by the config, or to the values in `config.json`.
> Replace '\n' in key/cert text with literal newlines

- src/app.js
This fixes an issue where the server would fail to start up when HTTPS was enabled, since ES Modules no longer support calling `require()` inside of them directly. I checked the rest of the code and there don’t seem to be any other `require` calls.
> Replace require with import

- src/app-account.js
- src/app.js
Corresponding PR for https://github.com/actualbudget/actual/pull/649. Also allows specifying relative paths for `webRoot` (such as `../actual/packages/desktop-client/build`, which is useful if you want to test running against a local build of the frontend).
> Auto-configure the client’s server URL

- .eslintrc.cjs
- .prettierrc.json
- migrations/1632571489012_remove_cache.js
- package.json
- src/app-account.js
- src/app-nordigen/app-nordigen.js
- src/app-nordigen/banks/bank.interface.ts
- src/app-nordigen/banks/ing-pl-ingbplpw.js
- src/app-nordigen/banks/integration-bank.js
- src/app-nordigen/banks/mbank-retail-brexplpw.js
- src/app-nordigen/banks/sandboxfinance-sfin0000.js
- src/app-nordigen/banks/tests/ing-pl-ingbplpw.spec.js
- src/app-nordigen/banks/tests/integration-bank.spec.js
- src/app-nordigen/banks/tests/mbank-retail-brexplpw.spec.js
- src/app-nordigen/banks/tests/sandboxfinance-sfin0000.spec.js
- src/app-nordigen/errors.js
- src/app-nordigen/nordigen.types.ts
- src/app-nordigen/services/nordigen-service.js
- src/app-nordigen/services/tests/fixtures.js
- src/app-nordigen/services/tests/nordigen-service.spec.js
- src/app-nordigen/tests/utils.spec.js
- src/app-nordigen/utils.js
- src/app-sync.js
- src/app-sync.test.js
- src/app.js
- src/load-config.js
- src/sync-simple.js
- src/util/validate-user.js
Two changes in this PR:
1. fail CI jobs if there are lint warnings
2. add trailing comas everywhere (this aligns `actual-server` with `actual`)
> :rotating_light:  adding trailing commas everywhere

- package.json
- src/app-nordigen/services/nordigen-service.js
- src/config-types.ts
- src/load-config.js
This _slightly_ changes the interface for configuring Nordigen, but IMO it's safe to do because
1. the nordigen support is still experimental and subject to breaking changes
2. we released 23.3.0 only an hour ago
> 🔖 (23.3.1) fix nordigen usage in fly.io

- Dockerfile
People have been having issues with this. I copied it from `docker/stable-ubuntu.Dockerfile`. We should follow up on this to remove the duplication at some point but this will help fix the problems people are having now.
> Don’t make Dockerfile a symlink

- src/app-nordigen/app-nordigen.js
- src/app-nordigen/link.html
When Nordigen accounts are linked 2x windows get opened: 1x (initial tab) is polling for the status; the other window is for authenticating with bank. Once the auth is done - customer is redirected back to app: `/nordigen/link` page. At this point we can just close the tab.
https://github.com/actualbudget/actual/issues/724#issuecomment-1462853590
> :bug: (nordigen) close window when opening /nordigen/link path

- src/app-nordigen/app-nordigen.js
- src/app-nordigen/services/nordigen-service.js
Add a small endpoint that will be used to check the configuration status of Nordigen. If it is not configured - we should not allow people to proceed in the account-link flow.
> :sparkles: (nordigen) add status endpoint for checking status

- src/app-nordigen/banks/integration-bank.js
- src/app-nordigen/banks/tests/integration-bank.spec.js
Sometimes accounts have the same names and the same IBAN, but different currencies (Paypal).
This should make the account names a bit more unique.. thus easier to distinguish.
https://github.com/actualbudget/actual/issues/724#issuecomment-1464902166
Obviously the user can choose to use different names in `Actual`. They are not forced to use this name.
> :bug: (nordigen) add currency to account name

- src/app-nordigen/app-nordigen.js
- upcoming-release-notes/168.md
Exposing the demo bank again in the get-banks endpoint.
Frontend implementation of the `showDemo` will come next. The demo bank will only be available for DEV and PREVIEW builds.
> :sparkles: (bank-sync) expose demo bank in the get-banks endpoint

- src/load-config.js
- upcoming-release-notes/167.md
This changes the behavior of configuration loading when ACTUAL_CONFIG_PATH env var is not specified. With this change, syntax errors in config.json will now be reported if ACTUAL_CONFIG_PATH env var is not specified and the app will not proceed. When the config.json file is not present or cannot be read, the behavior remains the same.
> Report parse issues for config.json in default location

- src/app-sync.js
- src/app-sync.test.js
- upcoming-release-notes/172.md
Briefly mentioned by @j-f1 here: https://discord.com/channels/937901803608096828/940290142579605514/1089653624390561822
I opted to keep the `500` HTTP code as is and therefore had to add a callback to `res.sendFile()` call and use a different code. I can instead update the test to check for `404` and remove the callback entirely.
This could be extended to `/upload-user-file` by removing the `application/actual-sync` and `application/encrypted-file` middleware and just use `req` as a stream by piping it into a file (with some added check for `Content-Length` header to ensure that we still have some max size for these files)
> Stream file without loading to memory in /download-user-file

- .github/workflows/docker-edge.yml
- .github/workflows/docker-release.yml
- README.md
- docker-compose.yml
- upcoming-release-notes/175.md
Update all Docker Hub references to new `actualbudget` organization from `jlongster` personal account. 
We're officially an org now!
A bit of markdown/yaml auto-formatting snuck in, too.
Closes https://github.com/actualbudget/actual/issues/364
Corresponding update for the docs site in https://github.com/actualbudget/docs/pull/144
Simultaneous to merging, we need to update our `DOCKER_HUB_*` GitHub secrets in this repo.
> :sparkles: New Docker Hub org in CI and README

- .github/workflows/docker-edge.yml
- .github/workflows/docker-release.yml
- docker/edge-alpine.Dockerfile
- docker/stable-alpine.Dockerfile
- upcoming-release-notes/182.md
GitHub CI log:
```
[linux/arm/v6 base 6/8] RUN yarn workspaces focus --all --production
204.6 ➤ YN0007: │ bcrypt@npm:5.1.0 must be built because it never has been before or the last one failed
204.6 ➤ YN0007: │ better-sqlite3@npm:8.2.0 must be built because it never has been before or the last one failed
...
[linux/arm/v7 base 6/8] RUN yarn workspaces focus --all --production
203.8 ➤ YN0007: │ bcrypt@npm:5.1.0 must be built because it never has been before or the last one failed
203.8 ➤ YN0007: │ better-sqlite3@npm:8.2.0 must be built because it never has been before or the last one failed
```
It seems that both armv6 and armv7 have the same issues with `bcrypt` and `better-sqlite3` not being built. These packages are required to build from source, luckily QEMU use armv7l for compiling. …
> Add support for armv6l (alpine based images)

- .github/workflows/docker-edge.yml
- .github/workflows/docker-release.yml
Honestly, I am not sure why the parallel build failed, even though parallel build succeed on `edge` with 2 threads. I hope someone more knowledgeable can contribute a better github action workflow
> github action workflow: revert old way to build images

- babel.config.json
- package.json
- upcoming-release-notes/185.md
- yarn.lock
Seems like we already added `tsc` to build the project, but we use the wrong babel preset (Flow) instead of the specific TS one. This is only used in testing to make Jest work (from what I can tell).
> Use babel preset-typescript

- package.json
- src/app.js
- upcoming-release-notes/187.md
- yarn.lock
CodeQL keeps yelling at us about this… I’m not sure if the filter is smart enough to use this rate limit middleware to remove the warnings, but at least we will be setting a reasonable bound on attempts to crack the server password.
> Add `express-rate-limit`

- package.json
- src/account-db.js
- src/app-account.js
- src/scripts/reset-password.js
- src/util/prompt.js
- src/util/validate-user.js
- upcoming-release-notes/186.md
This allows a couple of new workflows:
- setting the password before deploying the server, so that you don’t have to worry about an attacker bootstrapping it before you can
```shellsession
$ npm run reset-password
It looks like you don’t have a password set yet. Let’s set one up now!
Enter a password, then press enter: hunter2
Enter the password again, then press enter: hunter2
Password set!
```
- resetting the password without having to delete the server-files database (which includes the file list we would like to not have to delete!
```shellsession
$ npm run reset-password
It looks like you already have a password set. Let’s reset it!
Enter a password, then press enter: hunter2
Enter the password again, then press enter: hunter2
Password changed!
```
> Add a password set/reset script

- src/app-nordigen/app-nordigen.js
- upcoming-release-notes/189.md
This will help debug more clearly when Nordigen’s API returns unexpected status codes, since the current shape causes the actual response data to be collapsed in the console logs.
> Add a handler for AxiosError errors

- src/app-nordigen/app-nordigen.js
- src/app-nordigen/banks/bank.interface.ts
- src/app-nordigen/nordigen.types.ts
- src/app-nordigen/services/nordigen-service.js
- src/app-nordigen/services/tests/nordigen-service.spec.js
- upcoming-release-notes/190.md
Helps with actualbudget/actual#919 by adding the `all` field wit both pending and booked transactions to the output of `getTransactionsWithBalance()` and, by extension, the `/nordigen/transactions` endpoint.
I could alter the `getTransactions()` to return the `all` field as well but I figured that keeping it such that it returns the output from Nordigen API 1:1 might be better so I left it as is. If you don't agree, let me know and I'll update this.
> Add a field with all transactions to /nordigen/transactions endpoint

- .github/workflows/docker-edge.yml
- .gitignore
- README.md
- docker/download-artifacts.sh
- docker/edge-alpine.Dockerfile
- docker/edge-ubuntu.Dockerfile
- upcoming-release-notes/204.md
Previously, the latest artifact list was requested unauthenticated using `ADD "https://api.github.com/..." /tmp/artifacts.json`. While this works locally, on GitHub’s servers it seems that the per-IP rate limit was exceeded. There isn’t a way to get Docker to pass the `Authorization` header that I know of, so this work has been moved to an external shell script that pulls down the relevant data.
> Authenticate request for artifacts

- package.json
- src/scripts/health-check.js
- upcoming-release-notes/214.md
This allows running a health check from inside the container. Usage: `npm run health-check`. That may not work inside of Alpine containers, so you can do `node src/scripts/health-check.js` directly instead. Fixes #213.
> Add a health check script

- package.json
- src/app-sync.js
- src/sync-simple.js
- upcoming-release-notes/218.md
- yarn.lock
Using the new CRDT package instead of API.
> :recycle: (crdt) use actual-app/crdt package instead of api

- package.json
- src/app.js
- upcoming-release-notes/229.md
- yarn.lock
1. upgrade `nordigen-node` to 1.2.6 (which uses the new gocardless domain)
2. allow accessing `nordigen` functionality via `/gocardless` to unblock using the new API path in actual-web
> ⬆️ (nordigen-node) upgrade to v1.2.6

- docker-compose.yml
- src/config-types.ts
- src/load-config.js
- src/services/secrets-service.js
- upcoming-release-notes/235.md
Removing env var/config file support for Nordigen secrets. These have been migrated to the new `secrets` db table a while ago. We can now clean up the legacy implementation for these secrets.
> :fire: (nordigen) removing env var/config file support

- src/app-gocardless/gocardless.types.ts
- upcoming-release-notes/241.md
There appears to be no strong reason for explicitly limiting the end date to today, and it's preventing proper integration with Bank Norwegian whose value dates actually represent when the interest-free period for the transaction ends and is therefore in the future. (#237)
After this is merged we can then remove the corresponding field from the Actual application.
> Make endDate optional when downloading GoCardless transactions

- src/app-gocardless/README.md
- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/american-express-aesudef1.js
- src/app-gocardless/banks/bank.interface.ts
- src/app-gocardless/banks/ing-pl-ingbplpw.js
- src/app-gocardless/banks/integration-bank.js
- src/app-gocardless/banks/mbank-retail-brexplpw.js
- src/app-gocardless/banks/sandboxfinance-sfin0000.js
- src/app-gocardless/gocardless.types.ts
- src/app-gocardless/services/gocardless-service.js
- src/app-gocardless/services/tests/gocardless-service.spec.js
- src/app-gocardless/tests/bank-factory.spec.js
- upcoming-release-notes/239.md
The first commit has the same transaction normalization commit as #237.
> Add GoCardless bank integration for American Express AESUDEF1

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/american-express-aesudef1.js
- src/app-gocardless/banks/integration-bank.js
- src/app-gocardless/banks/norwegian-xx-norwnok1.js
- src/app-gocardless/gocardless-node.types.ts
- src/app-gocardless/tests/utils.spec.js
- src/app-gocardless/utils.js
- upcoming-release-notes/237.md
This adds explicit support for all branchs of Bank Norwegian to the GoCardless integration to work around the issue reported in actualbudget/actual#1392 where their use of `valueDate` does not match the NextGenPSD2 definition which is what we expect to receive from GoCardless.  To work around this we simply remove this field when normalizing transactions and let the Actual app use `bookingDate` instead.
Resolves actualbudget/actual#1392.
> Add NORWEGIAN-XX-NORWNOK1 GoCardless integration

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/fintro-be-gebabebb.js
- src/app-gocardless/gocardless-node.types.ts
- upcoming-release-notes/242.md
Implements https://github.com/actualbudget/actual/issues/1466
Replaces https://github.com/actualbudget/actual/pull/1490
Uses @kyrias transaction normalization from https://github.com/actualbudget/actual-server/pull/237
Note that due to https://github.com/actualbudget/actual/pull/745, in case of **pending** transactions 'atmPosName' will be used for both the payeename and the notes field. This is because pending transactions do not have a payee name yet, but they do have an atmPosName in the additionalInformation field that I'm using. I would argue that we should not blindly put remittanceinformation in the payee name field (except perhaps for some banks), but I'm not removing that in this PR.
> Add FINTRO_BE_GEBABEBB GoCardless integration (Include additionalInformation in notes)

- package.json
- src/app-gocardless/banks/american-express-aesudef1.js
- src/app-gocardless/banks/bank.interface.ts
- src/app-gocardless/banks/fintro-be-gebabebb.js
- src/app-gocardless/banks/ing-pl-ingbplpw.js
- src/app-gocardless/banks/integration-bank.js
- src/app-gocardless/banks/mbank-retail-brexplpw.js
- src/app-gocardless/banks/norwegian-xx-norwnok1.js
- src/app-gocardless/banks/sandboxfinance-sfin0000.js
- src/app-gocardless/banks/tests/sandboxfinance-sfin0000.spec.js
- src/app-gocardless/services/gocardless-service.js
- src/app-gocardless/services/tests/gocardless-service.spec.js
- upcoming-release-notes/243.md
- yarn.lock
Previously the Actual backend would default to using `valueDate` and
falling back to `bookingDate`.  According to the GoCardless
documentation[^0] we should prefer `bookingDate` if it's set, but the
different bank integrations vary greatly in how they use the date fields
and so for consistency we should instead let the Actual bank
integrations decide which is the correct date for any given transaction.
For any transaction without an appropriate date to return the
`normalizeTransaction` function should return `null` so that it's
filtered out until the bank provides the full transaction details.
The existing bank integrations for ING_PL_INGBPLPW and
MBANK_RETAIL_BREXPLPW were changed to retain the existing precedence
order, though I'm not sure which is the correct one for these banks.
[^0]: …
> Decide on transaction date during GoCardless transaction normalization

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/danskebank-dabno22.js
- upcoming-release-notes/244.md
This PR adds an integration for `DANSKEBANK_DABANO22`.
The issue here is mostly similar to that fixed in #237 (`valueDate` is handled similarly), except from the issues with pending transactions (I _think_).
I'm going to take a wild guess here and say that the other branches of Danske Bank private (`DANSKEBANK_DABAFIHH`, `DANSKEBANK_DABADKKK`, `DANSKEBANK_DABASESX`, `DANSKEBANK_DABAGB2B`) _most likely_ exhibit the same behavior? But since I can't validate this I've just enabled this for the NO branch currently. Would love some feedback on this.
Another issue here is that I've only validated this behavior for the credit account. I have a checking account but don't really use it so I have no data on what that looks like, although I would expect it to not have the same issues with …
> Add DANSKEBANK_DABANO22 integration

- src/load-config.js
- upcoming-release-notes/249.md
Solves #246 by loading the config from the project root if it exists there.
> Fix config file not being loaded from the project root by default

- docker-compose.yml
- src/app.js
- src/config-types.ts
- src/load-config.js
- upcoming-release-notes/245.md
The information contained in an actual budget is now much more detailed than it was previously. Doubling this file size should prevent errors
> Make file size uploads configurable via env vars

- docker/edge-alpine.Dockerfile
- docker/edge-ubuntu.Dockerfile
- upcoming-release-notes/265.md
If we don't verify that the repository ID is what we expected then we will pull artifacts from PRs where the source branch is `master`.
> Make edge builds fetch master builds from correct repository

- package.json
- upcoming-release-notes/268.md
- yarn.lock
Upgrading `better-sqlite3` to align with the version used on the frontend.
Frontend PR: https://github.com/actualbudget/actual/pull/1643
> :arrow_up:  upgrade better-sqlite3 to v8.6.0

- .github/workflows/docker-edge.yml
- .github/workflows/docker-release.yml
- upcoming-release-notes/260.md
Removing `jlongster/actual-server`. This was deprecated a long time ago ([April 2023](https://github.com/actualbudget/docs/blob/7a90e1e2c730dba00b23bca514db7361c4de2747/blog/2023-04-16-release-23.4.0.md?plain=1#L12)).
> :fire:  remove jlongster/actual-server package

- package.json
- upcoming-release-notes/260.md
- upcoming-release-notes/262.md
- upcoming-release-notes/268.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/1859
- server: https://github.com/actualbudget/actual-server/pull/273
- docs: https://github.com/actualbudget/docs/pull/274
> :bookmark: (23.11.0)

- src/app-gocardless/services/gocardless-service.js
- upcoming-release-notes/278.md
https://github.com/actualbudget/actual-server/pull/267 introduced a small regression: the client is re-created every time it is used. Obviously this causes some problems as the access tokens get reset very often..
Instead I am now using a singleton client that is mapped by the secrets. Meaning: when secrets change we will generate a new client.
> :bug: (gocardless) fix banksync - create singleton client

- docker-compose.yml
- upcoming-release-notes/274.md
Required by Podman Compose. Docker Compose should not care either way. The registry prefix is explicitly supported in the [compose file spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#image)
> Add "docker.io/" registry prefix to docker compose image

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/bnp-be-gebabebb.js
- upcoming-release-notes/285.md
Change the gocardless integration that works for Fintro (subbrand) to also work with the main institution (BNP) and another brand of the bank (Hello Bank). Also rename of the file to the main brand.
> Changed fintro specific bank integration to work with BNP and Hello Bank

- package.json
- upcoming-release-notes/267.md
- upcoming-release-notes/274.md
- upcoming-release-notes/275.md
- upcoming-release-notes/277.md
- upcoming-release-notes/278.md
- upcoming-release-notes/281.md
- upcoming-release-notes/282.md
- upcoming-release-notes/283.md
- upcoming-release-notes/285.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/2003
- server: https://github.com/actualbudget/actual-server/pull/286
- docs: https://github.com/actualbudget/docs/pull/284
> :bookmark: (23.12.0) darkmode, transaction locking, mobile updates and more

- src/config-types.ts
- src/load-config.js
- src/migrations.js
- upcoming-release-notes/289.md
This PR makes it so the `.migrations` file gets stored in the `dataDir` instead of the application root. This should fix #288 and https://github.com/actualbudget/actual/issues/2011.
> Store migrations statestore in datadir

- src/app-gocardless/README.md
- upcoming-release-notes/292.md
> :pencil: (gocardless) updated the docs - removed redundant information

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/spk-marburg-biedenkopf-heladef1mar.js
- src/app-gocardless/banks/tests/spk-marburg-biedenkopf-heladef1mar.spec.js
- src/app-gocardless/gocardless-node.types.ts
- src/app-gocardless/tests/bank-factory.spec.js
- upcoming-release-notes/297.md
Add GoCardless bank integration for Sparkasse Marburg-Biedenkopf (Germany).
> Add GoCardless bank integration for SPK_MARBURG_BIEDENKOPF_HELADEF1MAR

- Dockerfile
- docker/edge-alpine.Dockerfile
- docker/edge-ubuntu.Dockerfile
- docker/stable-alpine.Dockerfile
- docker/stable-ubuntu.Dockerfile
- upcoming-release-notes/300.md
---
category: Maintenance
authors: hkiang01
---
Non-root users for Dockerfiles
As a regular Node application, the default user doesn't need to be root. For why this is important, see [Why non-root containers are important for security](https://docs.bitnami.com/tutorials/why-non-root-containers-are-important-for-security)
> non-root users for Dockerfiles

- README.md
- upcoming-release-notes/299.md
- upcoming-release-notes/303.md
Its just a quick pull request since one of the url-s had a broken link
> Update README.md broken link

- package.json
- upcoming-release-notes/310.md
- yarn.lock
Update to the new released version to get https://github.com/nordigen/nordigen-node/pull/57
It looks like actual gocardless users only have until the 20th to rollout this change.
The email:
```
Dear user,
We are contacting you to make sure you are using an up-to-date base_url for the GoCardless Bank Account Data API.
This small but important change which should be easy to make for anyone in your team who has access to the production setup of your service. The new connection string should be:
https://bankaccountdata.gocardless.com/api/v2/
The legacy URLs such as [ob.nordigen.com](http://ob.nordigen.com/) and [ob.gocardless.com](http://ob.gocardless.com/) will stop working on the 20th of February.
If you are using any of our public libraries, they are updated and can be found here: …
```
> Update the nordigen-node gem to get new endpoints

- src/app-gocardless/services/gocardless-service.js
- upcoming-release-notes/311.md
Ensures the redirect page is auto-closed after linking
After we dropped the nordigen endpoint in https://github.com/actualbudget/actual-server/pull/293 this was no longer working.
(Closing the redirect page automatically will typically reveal the previous tab which is the waiting actual page, where you can then setup next steps)
> Fix the link page for gocardless

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/315.md
This pull request adds pending transaction support for SimpleFIN (for the accounts that support pending transactions).
It follows the lead of the GoCardless integration, by importing pending transactions initially as uncleared, and then clearing when the transactions post.
> Pending Transaction Support for SimpleFIN Integration

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/seb-privat.js
- upcoming-release-notes/316.md
Add SEB Private Bank integration to gocardless. Handle that SEB is sending the creditor name in additionalInfo.
> feat: add SEB Privat bank

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/seb-kort-bank-ab.js
- upcoming-release-notes/325.md
Add custom bank adapter for 'SEB Kort Bank AB' to properly sync credit card transactions.
* Flip transaction amount so purchases are listed as payments (related to #261 )
* Handle that SEB is sending the creditor name in additionalInfo (copied from #316)
* Balance calculation based on 'expected' balance type
> feat: add 'SEB Kort Bank AB' credit card support

- docker-compose.yml
- upcoming-release-notes/333.md
It can be difficult to see how to bind Actual server to a different port when using `docker compose`.  This adds a (commented out) environment variable for `ACTUAL_PORT` to make that more obvious to users.
> Add ACTUAL_PORT environment variable to docker-compose.yml

- package.json
- src/app-gocardless/app-gocardless.js
- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/american-express-aesudef1.js
- src/app-gocardless/banks/bank.interface.ts
- src/app-gocardless/banks/belfius_gkccbebb.js
- src/app-gocardless/banks/bnp-be-gebabebb.js
- src/app-gocardless/banks/danskebank-dabno22.js
- src/app-gocardless/banks/ing-ingddeff.js
- src/app-gocardless/banks/ing-pl-ingbplpw.js
- src/app-gocardless/banks/integration-bank.js
- src/app-gocardless/banks/mbank-retail-brexplpw.js
- src/app-gocardless/banks/norwegian-xx-norwnok1.js
- src/app-gocardless/banks/sandboxfinance-sfin0000.js
- src/app-gocardless/banks/seb-kort-bank-ab.js
- src/app-gocardless/banks/seb-privat.js
- src/app-gocardless/banks/sparnord-spnodk22.js
- src/app-gocardless/banks/spk-marburg-biedenkopf-heladef1mar.js
- src/app-gocardless/gocardless.types.ts
- src/app-gocardless/services/gocardless-service.js
- src/app-gocardless/services/tests/gocardless-service.spec.js
- upcoming-release-notes/334.md
- yarn.lock
Right now this shouldn't actually change anything because the Actual will only try to fetch at most 90 days worth of transactions anyway.  I'll file a PR for those changes if this is approved.
I set the values for the existing integrations based on [this spreadsheet](https://docs.google.com/spreadsheets/d/1EZ5n7QDGaRIot5M86dwqd5UFSGEDTeTRzEq3D9uEDkM/edit#gid=976380583) and [these](https://nordigen.zendesk.com/hc/en-gb/articles/13239212055581-EEA-180-day-access) [two](https://nordigen.zendesk.com/hc/en-gb/articles/6760902653085-Extended-history-and-continuous-access-edge-cases) documentation pages.
> Allow setting accessValidForDays and maxHistoricalDays per bank

- src/config-types.ts
- src/load-config.js
- src/migrations.js
- upcoming-release-notes/341.md
> Make running app.js cwd agnostic, extend config to allow changing dataDir

- src/account-db.js
- src/app-account.js
- upcoming-release-notes/342.md
Fixes #308 
This change makes `/account/login` consistent with other non-authenticated endpoints and adds a more descriptive error message when no password is provided in the request body.
Before
```sh
% curl -X POST http://localhost:5006/account/login                                                                                                                                                                                                                   
{"status":"error","reason":"internal-error"}
```
After
```sh
% curl -X POST http://localhost:5006/account/login …
```
> Make /admin/login return a descriptive error when no password is provided

- src/app-gocardless/banks/bnp-be-gebabebb.js
- upcoming-release-notes/345.md
Fixes #344 
As discussed on Discord, pending transactions do not come through from this bank with a valueDate set, only bookingDate.
However bookingDate is close enough to valueDate that the transaction will deduplicate when booked so we will use bookingDate until valueDate is available.
> Add backup date field for GoCardless transactions with bank BNP_BE_GEBABEBB

- package.json
- upcoming-release-notes/333.md
- upcoming-release-notes/334.md
- upcoming-release-notes/341.md
- upcoming-release-notes/342.md
- upcoming-release-notes/343.md
- upcoming-release-notes/345.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/2693
- server: https://github.com/actualbudget/actual-server/pull/351
- docs: https://github.com/actualbudget/docs/pull/352
> :bookmark: (24.5.0) mobile improvements and much more

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/spk-karlsruhe-karsde66.js
- upcoming-release-notes/346.md
Adds a gocardless formatter, to properly format transaction information. Previously, additional remittance information was not supplied at all, and some creditor names were not set. This made recognizing transactions hard for users.
Now, we pick out the best remittanceInformation that we find, and use a helpful order of possible data from the transaction as the creditorName.
Fixes #331
> Add gocardless support for Sparkasse Karlsruhe (Germany)

- src/app-gocardless/banks/seb-kort-bank-ab.js
- upcoming-release-notes/350.md
`SEB_KORT_AB_NO_SKHSFI21` behaves like `SEB_KORT_AB_SE_SKHSFI21`. Added `SEB_KORT_AB_NO_SKHSFI21` to the list of institutions in the bank adapter for SEB Kort. 
~~I'm not able to get the correct starting balance. It seems like the transactions array does not include the non-invoiced transactions, only the booked transactions. In the overview of transactions, however, the non-invoiced transactions are listed. The starting balance is missing the amount equivalent of the non-invoiced transactions. Could use some help here.~~
Seems like I am able to get the correct starting balance after all. I had to connect the accont to gocardless again for it to recalculate the starting balance.
> Extend bank adapter for SEB Kort

- src/app-gocardless/banks/bnp-be-gebabebb.js
- upcoming-release-notes/349.md
Ensure payee names don't contain transactional information when pulling in transactions from BNP bank with GoCardless.
> fill in creditor name for BNP bank transactions

- jest.config.json
- upcoming-release-notes/366.md
Currently, the generated `coverage/` folder is analyzed for coverage.  This ignores it.
> Ignore coverage folder in the coverage report.

- src/app-gocardless/banks/american-express-aesudef1.js
- src/app-gocardless/banks/bankinter-bkbkesmm.js
- src/app-gocardless/banks/belfius_gkccbebb.js
- src/app-gocardless/banks/bnp-be-gebabebb.js
- src/app-gocardless/banks/danskebank-dabno22.js
- src/app-gocardless/banks/ing-ingddeff.js
- src/app-gocardless/banks/ing-pl-ingbplpw.js
- src/app-gocardless/banks/mbank-retail-brexplpw.js
- src/app-gocardless/banks/norwegian-xx-norwnok1.js
- src/app-gocardless/banks/sandboxfinance-sfin0000.js
- src/app-gocardless/banks/seb-kort-bank-ab.js
- src/app-gocardless/banks/seb-privat.js
- src/app-gocardless/banks/sparnord-spnodk22.js
- src/app-gocardless/banks/spk-karlsruhe-karsde66.js
- src/app-gocardless/banks/spk-marburg-biedenkopf-heladef1mar.js
- upcoming-release-notes/362.md
The custom bank code typically copies/pastes an existing bank and then modifies it.  So there is a lot of duplicated code.  This is a first pass at refactoring to reuse the fallback code from `integration-bank.js` and avoid duplication.
NOTE: I do not have GoCardless and can not test for breaking changes.  The existing test suite still works but is quite lacking in coverage of these files.
> Refactor GoCardless bank code to avoid duplication

- src/app-gocardless/bank-factory.js
- src/app-gocardless/tests/bank-factory.spec.js
- upcoming-release-notes/367.md
The bank factory test suite was missing several GoCardless banks.  This updates it to the banks currently in master.  Future PRs to add more banks should ensure this file is updated with the new banks.
> Add GoCardless banks to the bank factory test suite.

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/tests/virgin_nrnbgb22.spec.js
- src/app-gocardless/banks/virgin_nrnbgb22.js
- upcoming-release-notes/360.md
This change adds handling in for Virgin Money (VIRGIN_NRNBGB22). They don't return `creditorName` or `debtorName` through GoCardless so all transactions use the unprocessed `remittanceInformationUnstructured` field which contains extra details that make creating rules harder.
> Add bank handler for `VIRGIN_NRNBGB22` (Virgin Money)

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/nationwide-naiagb21.js
- src/app-gocardless/banks/tests/nationwide-naiagb21.spec.js
- upcoming-release-notes/372.md
Nationwide returns pending transactions with a date representing the latest a transaction could be booked. This stops actual's deduplication logic from working as it only checks 7 days ahead/behind and the transactionID from Nationwide changes when a transaction is booked.
There is also a seperate issue where they sometimes return invalid transactionIds that can change in the future and with the merge of actualbudget/actual#2770 prevents deduplication with the original transaction.
I've reported this to gocardless, they've taken it to nationwide but unfortunately I received this back this morning.
An image below showing the issue caused by the transaction ID (these are the same transaction)
This has been discussed in Discord <#1148889147801604096> where it was suggested I upstream this …
> Add bank handler for `NATIONWIDE_NAIAGB21` (Nationwide)

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/375.md
This PR tries to provide better error handling for SimpleFIN.  First, sometimes the calls were never returning a response (they just `return` from the method) so this fixes that issues, which notifies the client side that something happened.
Second, it tries to provide better error messages on the client side.
> Properly handle errors for SimpleFIN.

- .github/workflows/stale.yml
- upcoming-release-notes/376.md
Same action as used in the main actual repository.
> :wrench: add github action for handling stale PRs

- src/app-gocardless/banks/seb-kort-bank-ab.js
- upcoming-release-notes/391.md
Relates to #261 
Add SEB Card Accounts institution ID to correctly import purchases as payments instead of deposits.
> Update SEB Credit Card adapter to include SEB Card Accounts

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/bank.interface.ts
- src/app-gocardless/banks/easybank-bawaatww.js
- src/app-gocardless/banks/tests/easybank-bawaatww.spec.js
- upcoming-release-notes/396.md
This enhances the parsing of payeeName for the Austrian bank easybank (BAWAATWW) as it is often left blank with the default implementation.
> Add gocardless support for easybank (Austria)

- package.json
- upcoming-release-notes/400.md
- Remove `-s` argument from the `verify` script which was erroring out
- Fixes #394
> Fix `verify` script

- src/app-gocardless/banks/nationwide-naiagb21.js
- upcoming-release-notes/406.md
People were hitting bugs in this handler in relation to the 8 day adjustment. The better approach to this is to just clamp the max date to today's.
> fix date calculation in Nationwide bank handler

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/410.md
When SimpelFIN is down, we get 502 errors.  The JSON tries to parse, and fails.  The last commit simply wrapped that in a reject, but then nothing ever catches that rejected promise.  This catches them and sends a failure response code, and then returns (and avoids the server crashing).
> Stop server crashing when SimpleFIN is down.

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/412.md
As reported in https://discord.com/channels/937901803608096828/1270489947320881286.
It seems sometimes the account ID can't be found in the response from SimpleFIN.  Not sure why exactly, but the least we can do is give a better error and some console logs to help figure out what happened.
> Show better error if SimpleFIN account cant be found.

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/413.md
Without this, the subsequent res.send() would throw an error for writing headers when another response has already been sent.
> Return early from SimpleFIN /transactions if the account needs attention

- src/app-gocardless/app-gocardless.js
- src/app-gocardless/services/gocardless-service.js
- src/app-gocardless/services/tests/gocardless-service.spec.js
- upcoming-release-notes/435.md
Part of #431 
IBAN wasn't actually used anywhere in the client side after it was returned by the server, removing the accountMetadata call results in one API call fewer per sync.
For easy checking:
https://github.com/actualbudget/actual/blob/af5fd5b3efeef1628ad583b661fa0539d4d0f63e/packages/loot-core/src/server/accounts/sync.ts#L119-L123
> 🧹 remove unused accountMetadata GoCardless API call on sync

- src/app-gocardless/app-gocardless.js
- src/app-gocardless/services/gocardless-service.js
- upcoming-release-notes/436.md
Depends on merge of #435 
Part of #431 
Complimentary to PR in actual: actualbudget/actual#3279
The balance fetched from gocardless is used to calculate the starting balance, which is only relevant when a completely blank account is synced. This change lays the groundwork in the server to allow the client side to be more selective in what it retrieves.
> 🧹 optimise GoCardless bank sync to use fewer api calls

- src/app-gocardless/banks/bankinter-bkbkesmm.js
- upcoming-release-notes/428.md
Before #353, `payeeName` would automatically fall back to `remittanceInformationUnstructured`. However, now it first falls back to `debtorName`, which I believe does not make much sense in this context.
Initially, I considered editing how the `payeeName` fallback works in `src/util/payee-name.js`. However, in the case of `BANKINTER_BKBKESMM`, when `creditorName` is not set, `remittanceInformationUnstructured` is actually the correct representation of the creditor's name. Therefore, I believe this fallback logic is appropriate for this scenario.
> Fallback creditorName to remittanceInformationUnstructured in BANKINTER_BKBKESMM

- src/util/payee-name.js
- upcoming-release-notes/429.md
Note: This PR depends on #427 to work properly.
Currently, if `creditorAccount` is not set in a payment but `debtorAccount` is, `payeeName` ends up being `"creditorName (debtorAccount)"`, which doesn't make sense. The issue is reversed in income transactions.
This situation always occurs in `BANKINTER_BKBKESMM` payments, where `creditorAccount` is never provided, but `debtorAccount` is always set.
To address this, I have prevented the account from falling back if the primary name option is set.
Additionally, consider whether we should ever fallback the account. We might also want to avoid falling back the name to the opposite (e.g., payments shouldn’t fallback to `debtorName` if `creditorName` is not set, and income shouldn’t fallback to `creditorName` if `debtorName` is not set). …
> Prevent account fallback if name is defined in formatPayeeName

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/kbc_kredbebb.js
- src/app-gocardless/banks/tests/kbc_kredbebb.spec.js
- upcoming-release-notes/442.md
Fixes https://github.com/actualbudget/actual/issues/3303
Since we only have the `remittanceInformationUnstructured` available to us to extract the payee (for negative amounts), writing a dedicated integration for this seems reasonable.
~I couldn't really test this any further as I ran into GoCardless rate limits 🙈 But the basic implementation was working.~ Seems to work for my accounts now.
> Fix wrong payeeName used for KBC_KREDBEBB

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/bancsabadell-bsabesbbb.js
- src/app-gocardless/banks/tests/bancsabadell-bsabesbbb.spec.js
- upcoming-release-notes/445.md
The goCardless API for this bank doesn't return creditor and debtor names with its appropriate role based on the transaction amount, which makes Actual infer an incorrect payee name. So we just use the remittance information directly.
Hopefully this is ok, first time contributing.
Great project!
> Fix BancSabadell payee name based on the transaction amount

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/cbc_cregbebb.js
- src/app-gocardless/banks/kbc_kredbebb.js
- src/app-gocardless/banks/tests/cbc_cregbebb.spec.js
- src/app-gocardless/banks/util/extract-payeeName-from-remittanceInfo.js
- upcoming-release-notes/451.md
Fixes [actualbudget/actual#3216](https://github.com/actualbudget/actual/issues/3216) (Complementary)
=> Incorrect payeeName for both KBC and CBC banks.
A first fix was implemented to support KBC bank but not for CBC (see: #442). 
This PR implements the same fallback logic as for KBC but for CBC bank (CBC_CREGBEBB).
\+ created helper function to prevent code-duplication
> fix: Wrong payeeName used for CBC_CREGBEBB

- upcoming-release-notes/README.md
Updated the link to the "Writing Good Release Notes" section due to resource relocation.
> Update link to "Writing Good Release Notes"

- src/app-gocardless/banks/bancsabadell-bsabesbbb.js
- src/app-gocardless/banks/tests/bancsabadell-bsabesbbb.spec.js
- upcoming-release-notes/474.md
Fixes a regression from a PR of mine from some weeks ago #445. I forgot to include the `date` field in the normalized transaction, which fails when syncing.
> fix: Sabadell Bank regression, missing date field during normalization

- src/load-config.js
- upcoming-release-notes/480.md
I need this for integration with electron. 
I need to tell actual-server where the data dir is so it knows where to place the .migrate file.
> Allowing data dir to be overridden

- app.js
- upcoming-release-notes/487.md
[This PR](https://github.com/actualbudget/actual-server/pull/432)  introduced a dependency in the app to have the user-files and server-files folders available. 
That's fine, but we need to ensure those folders exist before importing the app. If we don't the files-service will fail.
Related support thread: https://discord.com/channels/937901803608096828/1299430821509206160
> 🐛  Fix migrations not working on fresh clone

- src/app-gocardless/banks/easybank-bawaatww.js
- upcoming-release-notes/486.md
Fix linking accounts for easybank Austria:
Fixes #446
> Update easybank-bawaatww.js to change accessValidForDays: 179 from 180

- package.json
- upcoming-release-notes/432.md
- upcoming-release-notes/470.md
- upcoming-release-notes/473.md
- upcoming-release-notes/474.md
- upcoming-release-notes/478.md
- upcoming-release-notes/480.md
- upcoming-release-notes/481.md
- upcoming-release-notes/482.md
- upcoming-release-notes/483.md
- upcoming-release-notes/486.md
- upcoming-release-notes/487.md
- web: https://github.com/actualbudget/actual/pull/3766
- server: https://github.com/actualbudget/actual-server/pull/492
- docs: https://github.com/actualbudget/docs/pull/481
> 🔖 (24.11.0)

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/swedbank-habalv22.js
- src/app-gocardless/banks/tests/swedbank-habalv22.spec.js
- upcoming-release-notes/490.md
Extracts transaction date from `remittanceInformationUnstructured` for card transactions since it is not correct in the actual `bookedDate` and `valueDate` fields.
> Add support for SWEDBANK_HABALV22 transaction date

- src/app-gocardless/banks/ing-pl-ingbplpw.js
- upcoming-release-notes/493.md
Reported in Github, valueDate is more accurate for `ING_PL_INGBPLPW`
> `ING_PL_INGBPLPW` should prefer valueDate over bookingDate

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/504.md
The comparison here wasn't like for like and was always failing, resulting in the start date being ignored
> fix bug in batch SimpleFIN startDate logic

- src/app-gocardless/app-gocardless.js
- upcoming-release-notes/509.md
Unfortunately we can only get this information from the error object from the nordigen-node package. This just adds a little more info to the error sent to the client.
Complimentary PR: https://github.com/actualbudget/actual/pull/3895
> Return GoCardless rate limit information on error

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/isybank-itbbitmm.js
- upcoming-release-notes/510.md
Reported in Github, valueDate is more accurate for `ISYBANK_ITBBITMM`
> `ISYBANK_ITBBITMM` should prefer valueDate over bookingDate

- package.json
- upcoming-release-notes/506.md
- upcoming-release-notes/509.md
- upcoming-release-notes/510.md
- upcoming-release-notes/512.md
- upcoming-release-notes/513.md
- upcoming-release-notes/518.md
- upcoming-release-notes/523.md
- upcoming-release-notes/524.md
- upcoming-release-notes/526.md
- upcoming-release-notes/527.md
- upcoming-release-notes/528.md
- yarn.lock
- web: actualbudget/actual#4095
- server: #536
- docs: actualbudget/docs#601
> 🔖 (25.1.0)

- docker/edge-alpine.Dockerfile
- docker/edge-ubuntu.Dockerfile
- docker/stable-alpine.Dockerfile
- docker/stable-ubuntu.Dockerfile
- upcoming-release-notes/538.md
Further info https://docs.docker.com/reference/build-checks/from-as-casing/
> Fix WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/ssk-dusseldorf-dussdeddxxx.js
- upcoming-release-notes/531.md
This adds a gocardless formatter for the bank Stadtsparkasse Düsseldorf (Germany).
Mainly it fixes the creditor name for cases where payments are managed by a third-party provider by using the `ultimateCreditor` in addition to the other possible fields and fills the notes property.
> Add proper transaction formatting for Stadtsparkasse Düsseldorf (Germany)

- src/app-gocardless/banks/abnamro_abnanl2a.js
- src/app-gocardless/banks/tests/abnamro_abnanl2a.spec.js
- upcoming-release-notes/534.md
For payment made with google pay this also cleanes the payee_name.
Removes the removal of certain terms in the notes. As for me it really helpful to have BEA and GEA in the notes. (GEA is for atm withdraws) 
The cleaning should be achieved with https://github.com/actualbudget/actual/issues/3606 I think. @nsulzer would you be opposed by this?
> Improve abn amro sync

- src/app-gocardless/banks/ing-ingbrobu.js
- upcoming-release-notes/535.md
Hello,
I am updating my adapter for ING Romania. It seems there is a special transaction type (insurance provided by the bank itself for example), which does not have the `remittanceInformationUnstructured` field, only the `proprietaryBankTransactionCode` one.
This led to a `Cannot read properties of undefined (reading 'toLowerCase')` error, so no new transactions were synced. This commit fixes the issue.
> Corner case transaction for GoCardLess adapater (ING Romania)

- src/account-db.js
- src/app-account.js
- src/app.js
- src/config-types.ts
- src/load-config.js
- src/util/validate-user.js
- upcoming-release-notes/499.md
- Validate that the closest peer to the express server is trusted proxy
- Add a new trustedAuthProxies config to eventually be used for this
- Add a allowedLoginMethod config to enable fully disabling header auth
- uses the old trustedProxies config to configure express trust (to resolve https://github.com/actualbudget/actual-server/issues/392 at the same time)
Doc update PR: https://github.com/actualbudget/docs/pull/581
Fixes: https://github.com/actualbudget/actual-server/issues/371
Fixes: https://github.com/actualbudget/actual-server/issues/392
> fix: Fix the auth proxy trust by ensuring the proxy is in the trust

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/commerzbank_cobadeff.js
- src/app-gocardless/banks/tests/commerzbank_cobadeff.spec.js
- src/app-gocardless/gocardless-node.types.ts
- upcoming-release-notes/537.md
Add GoCardless integration for COMMERZBANK_COBADEFF, with a bunch of cleanup for remittance information that will become the notes. The source data for this bank is a bit messy to format unfortunately.
Question to the reviewer: Is the implementation of the optional `iban` property for `creditorAccount` correct/clean? Not a dev, sorry.
> Add GoCardless integration for COMMERZBANK_COBADEFF

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/lhv-lhvbee22.js
- src/app-gocardless/banks/tests/lhv-lhvbee22.spec.js
- upcoming-release-notes/542.md
Add GoCardless formatter for LHV Estonia (`LHV_LHVBEE22`).
This extracts bookingDate and creditorName for card transactions where creditorName is not provided originally (null) and bookingDate delayed until the card transaction clears a few days later. The current mainline version simply falls back to setting the payeeName to remittanceInformationUnstructured and this is not good, since the values are long and unique every time.
For example:
```
remittanceInformationUnstructured = '(..1234) 2025-01-02 09:32 CrustumOU\Poordi 3\Tallinn\10156     ESTEST'
```
will now yield these values
```
bookingDate = '2025-01-02'
creditorName = 'CrustumOU'
```
I tried to follow the pattern used by other bank integrations here and add a few test cases as well. I have been running this code on my server for …
> Add support for LHV_LHVBEE22

- src/app-gocardless/banks/ssk_dusseldorf_dussdeddxxx.js
- src/app-gocardless/banks/tests/ssk_dusseldorf_dussdeddxxx.spec.js
- upcoming-release-notes/553.md
The "Stadtsparkasse Düsseldorf" fills uncleared transactions with placeholder text. This text is not useful for human eyes or rule mapping. When the transaction is cleared the bank replaces the text with the correct payee and updates the notes. These don't get picked up on the next import, because the fields are already filled, therefore I removed the import of uncleared transactions.
> SSK_DUSSELDORF_DUSSDEDDXXX: remove non-booked transactions from import

- package.json
- upcoming-release-notes/499.md
- upcoming-release-notes/531.md
- upcoming-release-notes/533.md
- upcoming-release-notes/534.md
- upcoming-release-notes/535.md
- upcoming-release-notes/537.md
- upcoming-release-notes/538.md
- upcoming-release-notes/539.md
- upcoming-release-notes/541.md
- upcoming-release-notes/542.md
- upcoming-release-notes/546.md
- upcoming-release-notes/547.md
- upcoming-release-notes/550.md
- upcoming-release-notes/551.md
- upcoming-release-notes/553.md
- upcoming-release-notes/554.md
- yarn.lock
- web: actualbudget/actual#4296
- server: actualbudget/actual-server#561
- docs: actualbudget/docs#626
> 🔖 (25.2.0)
