actualbudget/actual-server

- .github/workflows/lint.yml
I forgot to add this to #33 but we should check the linting in CI on any PRs.
> Add linter checks to CI

- .gitignore
- load-config.js
- package.json
- sync-simple.js
- tsconfig.json
- yarn.lock
- adds basic typescript support. scripts for typechecking and compilation
- updated dockerfiles 
- include a build step
- best practices (with references in the commits). 
- The RUN consolidation might need discussion, as it could have an effect on caching that you find undesirable
- app-plaid.js seems to be unused. there's no plaid dependency in the the package, and I didnt spot any references to app-plaid. I haven't removed it, but it seems like a candidate for removal
- util/handle-error also unused
- sync-simple also unused
- No files have been rewritten to add typings or other TS specific changes in this PR. One fix was made as a result of running the typechecker.
- initial file conversion and very rough typings (ie there are still `any`s, which is unpleasant) in [a separate …
> Transition to typescript

- package.json
- yarn.lock
This version includes the import/export functionality on all platforms: https://github.com/actualbudget/actual/pull/71
> Bump Actual to 4.1.0

- app-sync.js
- sync-full.js
When I've tried to modify some account (add a transaction) on **second** computer, I've got "Your data is out of sync" error on first.
This PR should fix sync error message.
NOT Done:
- handle the encryptKeyId  for encrypted messages;
> Fix 'Out of sync' error

- package.json
- yarn.lock
Updated express version to 4.17, this resolves #69
> Update Express to version 4.17

- .eslintrc.js
- app-plaid.js
- app-sync.js
- app.js
- migrations/1632571489012_remove_cache.js
- sync-full.js
- sync-simple.js
- util/async.js
- util/error-middleware.js
- util/handle-error.js
As mentioned in #42, we aren't enforcing prettier rules. This PR adds prettier to the list of linting rules so that it's enforced by CI.
> Enforce prettier rules

- package.json
- yarn.lock
Actual 22.12.03 has been pushed, this updates the web and api packages
> Bump @actual-app/web and @actual-app/api

- package.json
- yarn.lock
The release has notable security improvements. Highlights:
* e2e encryption
* login invalidation when changing password
* dependency upgrades to remove potential actual-server security vulnerabilities (although we don’t believe there were any severe issues)
---
Release notes:
https://actualbudget.github.io/docs/Release-Notes
PR: https://github.com/actualbudget/docs/pull/84
> :bookmark: (23.2.5) security focused release

- package.json
- yarn.lock
Docs: https://github.com/actualbudget/docs/pull/119
> :bookmark: (23.3.0) experimental bank-sync, maintenance, fixes

- package.json
- src/app-nordigen/services/nordigen-service.js
- yarn.lock
This PR fixes the regeneration Nordigen token when it expires.
https://github.com/actualbudget/actual/issues/724
> Re-generate nordigen token

- LICENSE.txt
Same as https://github.com/actualbudget/actual/pull/665
> Remove year from the LICENSE

- package.json
- src/account-db.js
- src/load-config.js
- upcoming-release-notes/178.md
- yarn.lock
This will help people sort out configuration issues. Will open a PR to the docs as well to guide people to troubleshoot using this!
> Add some basic debug logging

- package.json
- upcoming-release-notes/141.md
- upcoming-release-notes/150.md
- upcoming-release-notes/165.md
- upcoming-release-notes/166.md
- upcoming-release-notes/167.md
- upcoming-release-notes/168.md
- upcoming-release-notes/171.md
- upcoming-release-notes/172.md
- upcoming-release-notes/175.md
- upcoming-release-notes/178.md
- yarn.lock
> :bookmark: (23.4.0)

- package.json
- upcoming-release-notes/181.md
- upcoming-release-notes/182.md
- upcoming-release-notes/185.md
- upcoming-release-notes/187.md
- yarn.lock
> :bookmark: (23.4.1) fix rule creation from transaction list

- package.json
- upcoming-release-notes/190.md
- upcoming-release-notes/194.md
- upcoming-release-notes/195.md
- upcoming-release-notes/197.md
- yarn.lock
> :bookmark: (23.5.0) various improvements

- README.md
- https://github.com/actualbudget/docs/pull/202
> Update “how it works” link

- README.md
> Contributing readme link update

- docker-compose.yml
Someone on discord had this issue.
> Update comments in docker-compose.yml

- package.json
- upcoming-release-notes/214.md
- upcoming-release-notes/218.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/1280
- server: https://github.com/actualbudget/actual-server/pull/222
- docs: https://github.com/actualbudget/docs/pull/223
> :bookmark: (23.7.0) Nordigen release, stability improvements

- package.json
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/1295
- server: https://github.com/actualbudget/actual-server/pull/224
- docs: https://github.com/actualbudget/docs/pull/225
> :bookmark: (23.7.1) critical sync fixes

- package.json
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/1322
- server: https://github.com/actualbudget/actual-server/pull/225
- docs: https://github.com/actualbudget/docs/pull/230
> :bookmark: (23.7.2) more patches (not so critical, but still annoying)

- package.json
- upcoming-release-notes/229.md
- upcoming-release-notes/231.md
- upcoming-release-notes/235.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/1444
- server: https://github.com/actualbudget/actual-server/pull/238
- docs: https://github.com/actualbudget/docs/pull/257
> :bookmark: (23.8.0) stability improvements and new experimental features

- package.json
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/1475
- server: https://github.com/actualbudget/actual-server/pull/240
- docs: https://github.com/actualbudget/docs/pull/260
> :bookmark: (23.8.1) fix nYNAB import, mobile colors and other smaller fixes

- src/app.js
- upcoming-release-notes/248.md
Resolves #247 by disabling the x-powered-by header
> Disable Express x-powered-by Header

- package.json
- upcoming-release-notes/237.md
- upcoming-release-notes/239.md
- upcoming-release-notes/241.md
- upcoming-release-notes/242.md
- upcoming-release-notes/243.md
- upcoming-release-notes/244.md
- upcoming-release-notes/248.md
- upcoming-release-notes/249.md
- yarn.lock
**Feature highlight:**
- Mobile transaction entry - ability to enter transactions using the mobile responsive version of Actual
- Privacy mode - ability to mask balance amounts in the app - allowing to use the product in public environments
---
- web: https://github.com/actualbudget/actual/pull/1635
- server: https://github.com/actualbudget/actual-server/pull/259
- docs: https://github.com/actualbudget/docs/pull/266
> :bookmark: (23.9.0) mobile transaction entry, privacy mode

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- upcoming-release-notes/262.md
Adding issue templates to this repo too.
> :wrench: (github) adding issue templates

- Dockerfile
- docker/edge-alpine.Dockerfile
- docker/edge-ubuntu.Dockerfile
- docker/stable-alpine.Dockerfile
- docker/stable-ubuntu.Dockerfile
- upcoming-release-notes/275.md
> :bug: (docker) add missing migrations folder

- package.json
- upcoming-release-notes/281.md
- yarn.lock
Should fix https://github.com/actualbudget/actual/issues/1905
Thanks @MikesGlitch
> :arrow_up: (node-migrate) upgraded to v2.0.1

- package.json
- upcoming-release-notes/289.md
- server: https://github.com/actualbudget/actual-server/pull/290
- docs: https://github.com/actualbudget/docs/pull/289
> :bookmark: (23.12.1) fix '.migrate' file causing Synology NAS problems

- package.json
- upcoming-release-notes/292.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/2177
- server: https://github.com/actualbudget/actual-server/pull/295
- docs: https://github.com/actualbudget/docs/pull/299
> :bookmark: (24.1.0) Mobile split transactions

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/ing-ingddeff.js
- src/app-gocardless/banks/tests/ing-ingddeff.spec.js
- upcoming-release-notes/294.md
> Add GoCardless bank integration for ING_INGDDEFF

- docker/edge-alpine.Dockerfile
- docker/edge-ubuntu.Dockerfile
- docker/stable-alpine.Dockerfile
- docker/stable-ubuntu.Dockerfile
- upcoming-release-notes/302.md
- improves ci stability
Potentially fixes https://github.com/actualbudget/actual-server/issues/287
> Limit yarn concurrency on 32bit

- package.json
- upcoming-release-notes/284.md
- upcoming-release-notes/293.md
- upcoming-release-notes/294.md
- upcoming-release-notes/296.md
- upcoming-release-notes/297.md
- upcoming-release-notes/298.md
- upcoming-release-notes/300.md
- upcoming-release-notes/302.md
- upcoming-release-notes/303.md
- yarn.lock
- client: https://github.com/actualbudget/actual/pull/2311
- server: https://github.com/actualbudget/actual-server/pull/306
- docs: https://github.com/actualbudget/docs/pull/308
> :bookmark: (24.2.0) cleared transaction improvements; experimental simplefin bank-sync

- .github/workflows/build.yml
- .github/workflows/docker-edge.yml
- .github/workflows/docker-release.yml
- .github/workflows/lint.yml
- .github/workflows/release-notes.yml
- .github/workflows/test.yml
- upcoming-release-notes/307.md
> :wrench: upgrade deprecated github actions

- package.json
- upcoming-release-notes/305.md
- upcoming-release-notes/307.md
- upcoming-release-notes/310.md
- upcoming-release-notes/311.md
- upcoming-release-notes/315.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/2413
- server: https://github.com/actualbudget/actual-server/pull/317
- docs: https://github.com/actualbudget/docs/pull/327
> :bookmark: (24.3.0)

- package.json
- upcoming-release-notes/316.md
- upcoming-release-notes/325.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/2537
- server: https://github.com/actualbudget/actual-server/pull/332
- docs: https://github.com/actualbudget/docs/pull/342
> :bookmark: (24.4.0) custom reports improvements, stability enhancements

- package.json
- upcoming-release-notes/312.md
- upcoming-release-notes/346.md
- upcoming-release-notes/349.md
- upcoming-release-notes/350.md
- upcoming-release-notes/355.md
- upcoming-release-notes/357.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/2819
- server: https://github.com/actualbudget/actual-server/pull/368
- docs: https://github.com/actualbudget/docs/pull/360
> :bookmark: (24.6.0)

- src/app-gocardless/banks/bnp-be-gebabebb.js
- upcoming-release-notes/370.md
> fix TypeError in GoCardless bnp-be-gebabebb sync

- package.json
- upcoming-release-notes/378.md
- yarn.lock
https://github.com/advisories/GHSA-78xj-cgh5-2h22
> :arrow_up: upgrade dependency tree to solve CVE-2023-42282

- package.json
- upcoming-release-notes/359.md
- upcoming-release-notes/360.md
- upcoming-release-notes/362.md
- upcoming-release-notes/366.md
- upcoming-release-notes/367.md
- upcoming-release-notes/370.md
- upcoming-release-notes/372.md
- upcoming-release-notes/375.md
- upcoming-release-notes/376.md
- upcoming-release-notes/378.md
- upcoming-release-notes/380.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/2955
- server: https://github.com/actualbudget/actual-server/pull/383
- docs: https://github.com/actualbudget/docs/pull/379
> :bookmark: (24.7.0) custom reports, splits in rules, tags and more

- src/app-gocardless/README.md
- src/app-gocardless/banks/sandboxfinance-sfin0000.js
- src/app-gocardless/banks/spk-karlsruhe-karsde66.js
- upcoming-release-notes/386.md
> Prettify GoCardless Bank Integration README

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/385.md
Changes the URL based on feedback from @iffy.
> Update URL to log into SimpleFIN.

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/ing-ingbrobu.js
- upcoming-release-notes/401.md
Hello,
I created a custom adapter for ING Bank (Romania). Due to issues with how the transactionId is populated by the bank, new transactions would not be imported to Actual. 
As I am not primarily a developer, feedback is greatly appreciated!
> Added GoCardless Integration for ING (Romania)

- package.json
- upcoming-release-notes/353.md
- upcoming-release-notes/385.md
- upcoming-release-notes/386.md
- upcoming-release-notes/388.md
- upcoming-release-notes/389.md
- upcoming-release-notes/390.md
- upcoming-release-notes/391.md
- upcoming-release-notes/396.md
- upcoming-release-notes/397.md
- upcoming-release-notes/400.md
- upcoming-release-notes/401.md
- upcoming-release-notes/402.md
- upcoming-release-notes/403.md
- upcoming-release-notes/405.md
- upcoming-release-notes/406.md
- upcoming-release-notes/407.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/3179
- server: https://github.com/actualbudget/actual-server/pull/408
- docs: https://github.com/actualbudget/docs/pull/421
> :bookmark: (24.8.0)

- src/app-simplefin/app-simplefin.js
- upcoming-release-notes/409.md
> Fix crash when SimpleFIN JSON data is bad.

- .github/workflows/stale.yml
- upcoming-release-notes/430.md
Copy stale workflow update from actualbudget/actual#3107
> add stale workflow update from actual

- src/app-sync.js
- src/app-sync.test.js
- upcoming-release-notes/423.md
~Needs https://github.com/actualbudget/actual-server/pull/421 to be merged first.~
Ready to be reviewed!
> add integration tests for the `/sync` endpoint

- src/util/payee-name.js
- upcoming-release-notes/427.md
Fixes actualbudget/actual#3216
> fix payee name selection based on the amount

- src/app-sync.js
- src/app-sync.test.js
- upcoming-release-notes/425.md
~Needs #423 to be merged first~
> add more tests for app-sync.js

- package.json
- upcoming-release-notes/358.md
- upcoming-release-notes/409.md
- upcoming-release-notes/410.md
- upcoming-release-notes/412.md
- upcoming-release-notes/413.md
- upcoming-release-notes/418.md
- upcoming-release-notes/421.md
- upcoming-release-notes/422.md
- upcoming-release-notes/423.md
- upcoming-release-notes/425.md
- upcoming-release-notes/427.md
- upcoming-release-notes/428.md
- upcoming-release-notes/429.md
- upcoming-release-notes/430.md
- upcoming-release-notes/434.md
- upcoming-release-notes/435.md
- upcoming-release-notes/436.md
- upcoming-release-notes/439.md
- upcoming-release-notes/441.md
- upcoming-release-notes/442.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/3348
- server: https://github.com/actualbudget/actual-server/pull/444
- docs: https://github.com/actualbudget/docs/pull/444
> :bookmark: (24.9.0)

- src/app-gocardless/banks/abanca-caglesmm.js
- upcoming-release-notes/455.md
Resolves https://discord.com/channels/937901803608096828/1284048444247511070 reported on Discord.
> add support for ABANCA_CAGLPTPL payee name

- package.json
- upcoming-release-notes/384.md
- upcoming-release-notes/445.md
- upcoming-release-notes/448.md
- upcoming-release-notes/449.md
- upcoming-release-notes/451.md
- upcoming-release-notes/452.md
- upcoming-release-notes/454.md
- upcoming-release-notes/455.md
- upcoming-release-notes/459.md
- upcoming-release-notes/465.md
- upcoming-release-notes/471.md
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/3545
- server: https://github.com/actualbudget/actual-server/pull/472
- docs: https://github.com/actualbudget/docs/pull/460
> :bookmark: (24.10.0)

- package.json
- yarn.lock
- web: https://github.com/actualbudget/actual/pull/3596
- server: https://github.com/actualbudget/actual-server/pull/475
- docs: https://github.com/actualbudget/docs/pull/465
> :bookmark: (24.10.1)

- yarn.lock
> [WIP] Update yarn.lock file

- src/app-gocardless/banks/swedbank-habalv22.js
- src/app-gocardless/banks/tests/swedbank-habalv22.spec.js
- upcoming-release-notes/497.md
- Tighten swedbank_habalv22 date regex
- Extract creditor name from remittance information for SWEDBANK_HABALV22
> Enrich pending transaction creditor info for SWEDBANK_HABALV22

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/hype_hyeeit22.js
- upcoming-release-notes/512.md
Enhances remittance information parsing for Hype Bank.
Fixes payee names including unwanted prefixes, unicode codepoints being escaped, remittance info including unneeded payee information on certain types of payements.
> Hype Bank (`HYPE_HYEEIT22`) Enhancements

- src/app-openid.js
- upcoming-release-notes/526.md
Error 500 when password invalid when disabling openid
> ⚙️Enchancement: Status code 500 for password invalid when disabling openid

- src/app-gocardless/bank-factory.js
- src/app-gocardless/banks/bank_of_ireland_b365_bofiie2d.js
- upcoming-release-notes/539.md
> :sparkles: add bank adapter for BOI

- README.md
- upcoming-release-notes/560.md
Adding a note to let people know we're moving Actual-Server into the Actual repo
> A note informing of the repo merge of actual-server into the actual repo

- package.json
- yarn.lock
What commits will be included in the release?
https://github.com/actualbudget/actual/compare/v25.2.1?expand=1
---
- web: https://github.com/actualbudget/actual/pull/4319
- server: https://github.com/actualbudget/actual-server/pull/565
- docs: https://github.com/actualbudget/docs/pull/628
> 🔖 (25.2.1) fix desktop apps and reports page
